const CONTROL_URL='https://clean.prismbayai.com/marketplace/ebay/control-plane.json';
const LISTING_URL='https://clean.prismbayai.com/marketplace/ebay/garment-steamer.json';
const state=document.getElementById('state');const openBtn=document.getElementById('open');const fillBtn=document.getElementById('fill');let control=null;let listing=null;
function esc(v){return String(v??'').replace(/[<>&]/g,'');}
function render(){const g=control?.gates||{};const ready=control?.readyForBrowserPublish===true;const lines=[['eBay authorization',g.ebaySellerAuthenticated],['CJ live stock',g.liveStockVerified],['Dispatch location',g.dispatchLocationVerified],['Off-eBay checkout absent',g.directStripeAbsent],['Auto supplier order disabled',g.automaticSupplierOrderingDisabled]];state.innerHTML=lines.map(([l,ok])=>`<div class="${ok?'ok':'bad'}">${ok?'✓':'✕'} ${esc(l)}</div>`).join('')+`<div class="small">${ready?'Ready for final eBay review.':'Draft fill is allowed, but final publish is not yet verified.'}<br>Checked ${esc(control?.checkedAt||'unknown')}</div>`;}
async function loadState(){try{const[c,l]=await Promise.all([fetch(`${CONTROL_URL}?t=${Date.now()}`,{cache:'no-store'}),fetch(`${LISTING_URL}?t=${Date.now()}`,{cache:'no-store'})]);if(!c.ok||!l.ok)throw new Error('state unavailable');control=await c.json();listing=await l.json();render();}catch{state.className='status bad';state.textContent='Verified marketplace state is unavailable. Final publish is blocked.';}}
async function activeEbayTab(){const[tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab||!/^https:\/\/(www\.)?ebay\.com\//i.test(tab.url||''))return null;return tab;}
openBtn.addEventListener('click',async()=>{await chrome.tabs.create({url:'https://www.ebay.com/sl/sell'});});
fillBtn.addEventListener('click',async()=>{const tab=await activeEbayTab();if(!tab){state.className='status bad';state.textContent='Open the eBay selling/listing page first.';return;}if(!listing||!control)return;const response=await chrome.tabs.sendMessage(tab.id,{type:'PRISMBAY_FILL',listing,control});state.className='status';state.textContent=response?.message||'Draft fill attempted.';});
loadState();
