const CONTROL_URL='https://clean.prismbayai.com/marketplace/ebay/control-plane.json';
const LISTING_URL='https://clean.prismbayai.com/marketplace/ebay/garment-steamer.json';
const AUTH_KEY='prismbayEbayAuth';
const EBAY_USER_ID='StudysmartzLLC';
const state=document.getElementById('state');const authBox=document.getElementById('auth');const connectBtn=document.getElementById('connect');const stopBtn=document.getElementById('stop');const openBtn=document.getElementById('open');const fillBtn=document.getElementById('fill');let control=null;let listing=null;
function esc(v){return String(v??'').replace(/[<>&]/g,'');}
function render(){const g=control?.gates||{};const ready=control?.readyForBrowserPublish===true;const lines=[['eBay authorization',g.ebaySellerAuthenticated],['CJ live stock',g.liveStockVerified],['Dispatch location',g.dispatchLocationVerified],['Off-eBay checkout absent',g.directStripeAbsent],['Auto supplier order disabled',g.automaticSupplierOrderingDisabled]];state.innerHTML=lines.map(([l,ok])=>`<div class="${ok?'ok':'bad'}">${ok?'✓':'✕'} ${esc(l)}</div>`).join('')+`<div class="small">${ready?'Ready for final eBay review.':'Final publish remains blocked until every gate is green.'}<br>Checked ${esc(control?.checkedAt||'unknown')}</div>`;connectBtn.disabled=g.ebaySellerAuthenticated===true;connectBtn.textContent=g.ebaySellerAuthenticated===true?`${EBAY_USER_ID} already connected`:`Connect ${EBAY_USER_ID} to CJ`;}
async function loadState(){try{const[c,l]=await Promise.all([fetch(`${CONTROL_URL}?t=${Date.now()}`,{cache:'no-store'}),fetch(`${LISTING_URL}?t=${Date.now()}`,{cache:'no-store'})]);if(!c.ok||!l.ok)throw new Error('state unavailable');control=await c.json();listing=await l.json();render();}catch{state.className='status bad';state.textContent='Verified marketplace state is unavailable. Final publish is blocked.';}}
async function loadAuth(){const o=await chrome.storage.local.get(AUTH_KEY);const s=o[AUTH_KEY];if(!s){authBox.className='status';authBox.textContent='Authorization runner idle.';return;}const cls=s.phase==='done'?'ok':String(s.phase||'').startsWith('blocked')||s.phase==='expired'?'bad':'wait';authBox.className=`status ${cls}`;authBox.textContent=s.status||`Phase: ${s.phase||'unknown'}`;}
async function activeEbayTab(){const[tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab||!/^https:\/\/([^.]+\.)?ebay\.com\//i.test(tab.url||''))return null;return tab;}
connectBtn.addEventListener('click',async()=>{const run={active:true,phase:'verify_ebay_account',userId:EBAY_USER_ID,startedAt:Date.now(),updatedAt:Date.now(),status:`Opening eBay to verify the signed-in account is ${EBAY_USER_ID}…`};await chrome.storage.local.set({[AUTH_KEY]:run});await loadAuth();await chrome.tabs.create({url:'https://www.ebay.com/'});});
stopBtn.addEventListener('click',async()=>{const o=await chrome.storage.local.get(AUTH_KEY);const s=o[AUTH_KEY]||{};await chrome.storage.local.set({[AUTH_KEY]:{...s,active:false,phase:'stopped',status:'Authorization run stopped.',updatedAt:Date.now()}});await loadAuth();});
openBtn.addEventListener('click',async()=>{await chrome.tabs.create({url:'https://www.ebay.com/sl/sell'});});
fillBtn.addEventListener('click',async()=>{const tab=await activeEbayTab();if(!tab){state.className='status bad';state.textContent='Open the eBay selling/listing page first.';return;}if(!listing||!control)return;const response=await chrome.tabs.sendMessage(tab.id,{type:'PRISMBAY_FILL',listing,control});state.className='status';state.textContent=response?.message||'Draft fill attempted.';});
chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes[AUTH_KEY])loadAuth();});
loadState();loadAuth();setInterval(loadAuth,1200);
